config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'sessions#welcome', as: 'root'
  # get 'music_app/index'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  get 'authorized' , to: 'sessions#page_requires_login'
  post 'add_song', to: 'songs#add_song_to_playlist'
  resources :albums, only: [:index, :show]
  # resources :genres
  resources :artists, only: [:index, :show]
  resources :songs, only: [:index, :show]
  resources :playlists, only: [:index, :show]
  resources :playlists do
    delete 'remove_song'
  end
  resources :songs_in_playlists, only: [:new, :create]
  resources :users, only: [:new, :show]
  resources :users do 
    resources :playlists, module: :users 
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/playlist.rb
class Playlist < ApplicationRecord
    belongs_to :playable, :polymorphic => true 
    has_many :songs_in_playlists, dependent: :destroy
    has_many :songs, through: :songs_in_playlists, dependent: :destroy
    validates :name, uniqueness: true, presence: true

    def playlist_search(search)
        if search  
            self.songs.where("lower(name) LIKE ?", "%" + search.downcase + "%")
        else
            self.songs
        end
    end

    def playlist_show(search)
        self.playlist_search(search).map { |song|
            {song_name: song.name,
            song_id: song.id,
            album_id: song.album_id,
            album_name: song.album.name,
            artist_id: song.album.artist_id,
            artist_name: song.album.artist.name,
             release_year: song.album.release_year}
        }
    end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
    before_action :set_playlist, only: [:show, :update, :destroy, :remove_song]
    def show
        @songs = @playlist.playlist_show(params[:search])
    end

    def index
        @playlists = current_user.playlists
        @user = current_user
    end

    def new
        @playlist = Playlist.new
    end

    def create
        @playlist = Playlist.create playlist_params
        if @playlist.valid?
            redirect_to @playlist
        else
            flash[:errors] = @playlist.errors.full_messages
            redirect_to playlists_path
        end
    end

    def destroy
        @playlist.destroy
        redirect_to playlists_path
    end

    def remove_song
        SongsInPlaylist.find_by(playlist_id: @playlist.id, song_id: params[:song_id]).destroy
        redirect_to @playlist
    end

    private 

    def set_playlist
        @playlist = Playlist.find(params[:id])
    end

    def playlist_params
        params.require(:playlist).permit(:name, :playable_type, :playable_id)
    end

end

app/controllers/songs/playlists_controller.rb
class Songs::PlaylistsController < PlaylistsController
    before_action :set_playable

    private 

    def set_playable
        @playable = Song.find(params[:song_id])
    end
end

app/controllers/users/playlists_controller.rb
class Users::PlaylistsController < PlaylistsController
    before_action :set_playable

    private 

    def set_playable
        @playable = User.find(params[:user_id])
    end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/playlists/_form.erb
<%= form_for [playable, Playlist.new] do |f| %>
    <div class="form-group col-sm-3">
        <%= f.text_field :name, class:"search-line", placeholder: "Playlist Name" %>
    </div>
    <%= f.hidden_field :playable_type, :value => "User" %>
    <%= f.hidden_field :playable_id, :value => playable.id %>
    <%= f.submit class: "btn btn-success" %>
<% end %>

<div class="text-danger">
  <% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
      <%= error %> <br>
    <% end %>
  <% end %>
</div>

app/views/playlists/_playlists.erb
<div class="container">
    <div class="row g-2">
        <% playable.playlists.each do |playlist| %> 
            <div class="col-6">
                <h4 class="p-3 bg-dark"> 
                    <%= link_to playlist.name, playlist, class: 'text-success' %> 
                </h4> 
            </div>
        <% end %>
    </div>
</div>   

app/views/playlists/index.erb
<h1 class="text-white"> Your Playlists</h1>

<div class="container">
    <div class="row g-2">
        <% current_user.playlists.each do |playlist| %> 
            <div class="col-6">
                <h4 class="p-3 bg-dark"> 
                    <%= link_to playlist.name, playlist, class: 'text-success' %> 
                </h4> 
            </div>
        <% end %>
    </div>
</div>

<%= render partial: "playlists/form", locals: {playable: @user}%>

app/views/playlists/show.erb
<h1 class="text-white"><%= @playlist.name %></h1>

<%= form_tag(playlist_path, method: :get) do%>
  <form class="form-inline md-form mr-auto mb-4">
    <%= text_field_tag :search, params[:search], class: 'search-line mr-sm-2', placeholder: 'Search by name'%>
  </form>
<%end%> <br>

<table class="table table-dark table-striped">
    <thead>
        <tr>
            <th style="width:40%" scope="col">Name</th>
            <th style="width:25%" scope="col">Artist</th>
            <th style="width:25%" scope="col">Album</th>
            <th style="width:7%" scope="col">Year</th>
            <th style="width:3%" scope="col">Remove</th>
        </tr>
    </thead>
    <tbody>
        <% @songs.each do |song| %>
            <tr>
                <td class="text-white"><%=link_to song[:song_name], song_path(song[:song_id]), class: 'text-white'%> </td>
                <td class="text-white"><%=link_to song[:artist_name], artist_path(song[:artist_id]), class: 'text-white'%> </td>
                <td class="text-white"><%=link_to song[:album_name], album_path(song[:album_id]), class: 'text-white'%></td>
                <td><%=song[:release_year]%> </td>
                <td><%= button_to "delete", playlist_remove_song_path(@playlist.id), params: {id: @playlist.id, song_id: song[:song_id]}, :method => :delete, class: 'btn btn-outline-light'%></td>
            </tr>
        <%end%>
    </tbody>
</table><br>

<%= button_to "Find songs", songs_path, :method => :get, class: 'btn btn-success'%> <br>
<%= button_to "Delete Playlist", @playlist, :method => :delete, class: 'btn btn-outline-light'%>